export const actionTypes : Record<string , string> = {
	ADD_TO_CART: 'ADD_TO_CART',
	REMOVE_FROM_CART: 'REMOVE_FROM_CART',
	UPDATE_CART_QUANTITY: 'UPDATE_CART_QUANTITY',
	UPDATE_CART_ITEM_QUANTITY: 'UPDATE_CART_ITEM_QUANTITY',
	UPDATE_CART_ITEM_PRICE: 'UPDATE_CART_ITEM_PRICE',
	TOGGLE_MENU: 'TOGGLE_MENU',
}
